// flow-typed signature: 14209814871a2ce520f3b8df605d7632
// flow-typed version: <<STUB>>/react-localization_v^0.1.3/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-localization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-localization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-localization/lib/LocalizedStrings' {
  declare module.exports: any;
}

declare module 'react-localization/lib/utils' {
  declare module.exports: any;
}

declare module 'react-localization/spec/LocalizedStrings.spec' {
  declare module.exports: any;
}

declare module 'react-localization/spec/utils.spec' {
  declare module.exports: any;
}

declare module 'react-localization/src/LocalizedStrings' {
  declare module.exports: any;
}

declare module 'react-localization/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-localization/lib/LocalizedStrings.js' {
  declare module.exports: $Exports<'react-localization/lib/LocalizedStrings'>;
}
declare module 'react-localization/lib/utils.js' {
  declare module.exports: $Exports<'react-localization/lib/utils'>;
}
declare module 'react-localization/spec/LocalizedStrings.spec.js' {
  declare module.exports: $Exports<'react-localization/spec/LocalizedStrings.spec'>;
}
declare module 'react-localization/spec/utils.spec.js' {
  declare module.exports: $Exports<'react-localization/spec/utils.spec'>;
}
declare module 'react-localization/src/LocalizedStrings.js' {
  declare module.exports: $Exports<'react-localization/src/LocalizedStrings'>;
}
declare module 'react-localization/src/utils.js' {
  declare module.exports: $Exports<'react-localization/src/utils'>;
}
